from sqlalchemy import text
from sqlalchemy.orm import Session


def truncate_workout_data(db: Session) -> None:
    """
    Postgres-only.

    Wipes tables that are generated by our test seeds so we can re-run seeding safely.

    Adjust table names if yours differ.
    """
    # Order doesn't matter with CASCADE, but keep it readable.
    db.execute(text("TRUNCATE TABLE set_logs RESTART IDENTITY CASCADE;"))
    db.execute(text("TRUNCATE TABLE exercise_logs RESTART IDENTITY CASCADE;"))
    db.execute(text("TRUNCATE TABLE workout_logs RESTART IDENTITY CASCADE;"))
    db.execute(text("TRUNCATE TABLE users RESTART IDENTITY CASCADE;"))
    db.execute(text("TRUNCATE TABLE goals RESTART IDENTITY CASCADE;"))
    db.commit()
    print("🧹 Truncated goals/users/workout tables (ready to reseed).")
